import "dotenv/config";
// Writes docs/openapi.json and the endpoint table in docs/api-reference.md from the live routers.
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { openapiDocument, operations } from "../src/docs/openapi.js";

const root = resolve(import.meta.dirname, "../..");
writeFileSync(resolve(root, "docs/openapi.json"), `${JSON.stringify(openapiDocument(), null, 2)}\n`);
const rows = operations()
  .map((op) => `| ${op.method.toUpperCase()} | \`${op.path}\` | ${op.roles ? op.roles.join(", ") : op.authenticated ? "any signed-in" : "public"} |`)
  .join("\n");
writeFileSync(
  resolve(root, "docs/api-reference.md"),
  `# API reference\n\nGenerated by \`npm run docs:api\` from the routers; the full schema is [openapi.json](./openapi.json) (also served at \`GET /api/v1/openapi.json\`). Conventions are in [api.md](./api.md).\n\n| Method | Path | Who |\n|---|---|---|\n${rows}\n`,
);
console.log(`Documented ${operations().length} operations`);
